
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package FaseCompilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menorigual = 15;
  public static final int cadena = 26;
  public static final int texto = 5;
  public static final int decimal = 3;
  public static final int promedio = 24;
  public static final int coma = 7;
  public static final int archivo = 19;
  public static final int numero = 21;
  public static final int imprimir = 28;
  public static final int contarsi = 25;
  public static final int leerarchivo = 20;
  public static final int eqa = 13;
  public static final int pa_close = 18;
  public static final int equals = 12;
  public static final int menos = 9;
  public static final int menor = 10;
  public static final int mayorigual = 16;
  public static final int obtenersi = 27;
  public static final int EOF = 0;
  public static final int id = 4;
  public static final int contar = 23;
  public static final int error = 1;
  public static final int pa_open = 17;
  public static final int entero = 2;
  public static final int graficar = 29;
  public static final int mas = 8;
  public static final int diferente = 14;
  public static final int suma = 22;
  public static final int puntoycoma = 6;
  public static final int mayor = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "entero",
  "decimal",
  "id",
  "texto",
  "puntoycoma",
  "coma",
  "mas",
  "menos",
  "menor",
  "mayor",
  "equals",
  "eqa",
  "diferente",
  "menorigual",
  "mayorigual",
  "pa_open",
  "pa_close",
  "archivo",
  "leerarchivo",
  "numero",
  "suma",
  "contar",
  "promedio",
  "contarsi",
  "cadena",
  "obtenersi",
  "imprimir",
  "graficar"
  };
}

